sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev
      - python
      - python-virtualenv
      - python-pip
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - librsvg2-bin
      - lua5.1
      - liblua5.1-0-dev
      - inotify-tools
      - python-dev
      - libxml2-dev
      - libxslt1-dev

language: csharp
mono:
  - latest

before_install:
  # Luarocks
  - wget http://keplerproject.github.io/luarocks/releases/luarocks-2.2.0.tar.gz
  - tar -xf luarocks-2.2.0.tar.gz
  - cd luarocks-2.2.0
  - ./configure
  - make build
  - sudo make install
  - cd ..
  - rm -rf luarocks-2.2.0 luarocks-2.2.0.tar.gz
  # Bazel
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-jdk7-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.4-jdk7-installer-linux-x86_64.sh
  - ./bazel-0.1.4-jdk7-installer-linux-x86_64.sh --user
  - cat tools/travis-ci/.bazelrc >> .bazelrc
  # KSP libraries
  - mkdir lib/ksp
  - wget --quiet -O lib/ksp/ksp-lib-1.0.5.tar.gpg https://s3.amazonaws.com/krpc/ksp-lib-1.0.5.tar.gpg
  - (cd lib/ksp; gpg --no-tty --batch --yes --passphrase $KSP_LIB_1_0_5_KEY ksp-lib-1.0.5.tar.gpg)
  - (cd lib/ksp; tar -xf ksp-lib-1.0.5.tar)

script:
  - bazel build //:krpc //doc:html && bazel test //:test

after_script:
  # Remove KSP libraries
  - rm -rf lib/ksp
