sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      - openjdk-7-jdk
      - openjdk-7-source
      - pkg-config
      - zip
      - zlib1g-dev
      - python
      - python-virtualenv
      - python-pip
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - librsvg2-bin
      - lua5.1
      - liblua5.1-0-dev
      - inotify-tools
      - python-dev
      - libxml2-dev
      - libxslt1-dev

language: csharp
mono:
  - latest

install:
  - ./tools/travis-ci/install-luarocks.sh
  - ./tools/tracis-ci/install-bazel.sh
  - ./tools/travis-ci/install-ksp-libs.sh

script:
  - bazel build //:krpc //doc:html //:csproj
  - xbuild KRPC.sln
  - bazel test //:test

after_script:
  - rm -rf lib/ksp
