name: "🚀 Feature Request"
description: Suggest a new feature for kRPC!
labels: ['enhancement', 'needs-triage']
title: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature.

  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
    validations:
      required: true

  - type: textarea
    id: reasoning
    attributes:
      label: Why is this needed?
    validations:
      required: true
