name: "🚀 kRPC Feature request"
description: Suggest a new feature/enhancement for kRPC!
labels: ['feature', 'request']
title: '[feat req]'
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please check existing issues to avoid making duplicates. Any duplicate issue will be closed immediately.
    validations:
      required: true

  - type: textarea
    id: reasoning
    attributes:
      label: Why is this needed?
    validations:
      required: true
