name: "📑 kRPC Documentation issues"
description: Found a kRPC documentation error? Help us correct it!
labels: ['documentation', 'request']
title: '[Enter a docs issue title]'
body:
  - type: markdown
    attributes:
      value: |
        ❗ This is for all kRPC documentation hosted by this repository including....`README.md`, `Contributing,md`, and `Development-Guide.md`

        The kRPC docs are located here 👉 [kRPC Documentation](https://krpc.github.io/krpc/)
  - type: textarea
    id: affected
    attributes:
      label: Where is the issue located?
      description: |
        Please provide links or provide the location of the issue.
    validations:
      required: false

  - type: textarea
    id: suggested
    attributes:
      label: What are your suggested changes?
      description: |
        Give as much detail as you can to help us understand the changes you want to see.
    validations:
      required: true
