runs:
  using: composite
  steps:
    - name: restore-bazel-cache
      id: bazel-cache
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/bazel
        key: bazel-cache-${{ hashFiles('WORKSPACE') }}
    - if: ${{ steps.bazel-cache.cache-hit != 'true' }}
      run: bazel fetch //...
      shell: bash
    - if: ${{ steps.bazel-cache.cache-hit != 'true' }}
      name: save-bazel-cache
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/bazel
        key: bazel-cache-${{ hashFiles('WORKSPACE') }}
