name: ci

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: |
          bazel build \
            //:krpc \
            //:csproj \
            //tools/krpctools \
            //tools/TestServer:archive
      - name: save-build-cache
        uses: actions/cache/save@v3
        id: build-cache
        with:
          path: ~/.cache/bazel
          key: ${{ env.GITHUB_RUN_NUMBER }}-${{ env.GITHUB_RUN_ATTEMPT }}
      - name: collect-artifacts
        run : |
          tools/dist/genfiles.sh
          mkdir deploy
          cp bazel-bin/krpc-*.zip deploy/
          cp bazel-bin/tools/krpctools/krpctools-*.zip deploy/
          cp bazel-bin/tools/TestServer/TestServer-*.zip deploy/
          cp bazel-bin/krpc-genfiles-*.zip deploy/
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          path: deploy

  build-docs:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: restore-build-cache
        uses: actions/cache/restore@v3
        id: build-cache
        with:
          path: ~/.cache/bazel
          key: ${{ env.GITHUB_RUN_NUMBER }}-${{ env.GITHUB_RUN_ATTEMPT }}
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: bazel build //doc:html

  test-server:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: restore-build-cache
        uses: actions/cache/restore@v3
        id: build-cache
        with:
          path: ~/.cache/bazel
          key: ${{ env.GITHUB_RUN_NUMBER }}-${{ env.GITHUB_RUN_ATTEMPT }}
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //server:ci-test

# job: compile docs scripts
#   bazel build //doc:compile-scripts

# job: build using sln file
#   msbuild KRPC.sln /t:Clean,Build -p:Configuration=Debug /warnaserror
#   msbuild KRPC.sln /t:Clean,Build -p:Configuration=Release /warnaserror

# multiple jobs from following:
#   bazel test //:ci-test
#   client/cpp/test-build.sh
#   client/cnano/test-build.sh
