name: ci

on: pull_request

jobs:
  build-krpc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: build
        run: |
          bazel build \
            //:krpc \
            //:csproj \
            //tools/krpctools \
            //tools/TestServer:archive
      - name: collect-artifacts
        run: |
          mkdir deploy
          cp bazel-bin/krpc-*.zip deploy/
          cp bazel-bin/tools/krpctools/krpctools-*.zip deploy/
          cp bazel-bin/tools/TestServer/TestServer-*.zip deploy/
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: deploy

  build-genfiles:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: build
        run: |
          tools/dist/genfiles.sh
          cp bazel-bin/krpc-genfiles-*.zip ./
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: genfiles
          path: krpc-genfiles-*.zip

  build-csharp-sln:
    needs: build-genfiles
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: download-genfiles
        uses: actions/download-artifact@v3
        with:
          name: genfiles
      - name: extract-genfiles
        run: |
          unzip krpc-genfiles-*.zip -d ./
          rm krpc-genfiles-*.zip
      - name: build
        run: |
          msbuild KRPC.sln /t:Clean,Build -p:Configuration=Debug /warnaserror
          msbuild KRPC.sln /t:Clean,Build -p:Configuration=Release /warnaserror

  build-docs-html:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: build
        run: bazel build //doc:html

  build-docs-pdf:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: build
        run: bazel build //doc:pdf

  test-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: build
        run: |
          bazel test //doc:test
          bazel build //doc:compile-scripts

  test-server:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //server:test

  test-client-cnano:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/cnano:test

  test-client-cpp:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/cpp:test --cache_test_results=no

  test-client-csharp:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/csharp:test

  test-client-java:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/java:test

  test-client-python:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/python:test

  test-client-lua:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/lua:test

  test-client-serialio:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/serialio:test

  test-client-websockets:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: bazel test //client/websockets:test

  test-tools:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: fetch
        uses: ./.github/actions/bazel-fetch
      - name: test
        run: |
          bazel test \
            //tools/krpctest:test \
            //tools/krpctools:test
