name: ci

on: pull_request

jobs:
  build-krpc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: |
          bazel build \
            //:krpc \
            //:csproj \
            //tools/krpctools \
            //tools/TestServer:archive
      - name: collect-artifacts
        run: |
          tools/dist/genfiles.sh
          mkdir deploy
          cp bazel-bin/krpc-*.zip deploy/
          cp bazel-bin/tools/krpctools/krpctools-*.zip deploy/
          cp bazel-bin/tools/TestServer/TestServer-*.zip deploy/
          cp bazel-bin/krpc-genfiles-*.zip deploy/
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          path: deploy

  build-csharp-sln:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: |
          msbuild KRPC.sln /t:Clean,Build -p:Configuration=Debug /warnaserror
          msbuild KRPC.sln /t:Clean,Build -p:Configuration=Release /warnaserror

  build-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: bazel build //doc:html

  test-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: build
        run: |
          bazel test //doc:ci-test
          bazel build //doc:compile-scripts

  test-server:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //server:ci-test

  test-client-cnano:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/cnano:ci-test
      - name: test-build
        run: client/cnano/test-build.sh

  test-client-cpp:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/cpp:ci-test &&
      - name: test-build
        run: client/cpp/test-build.sh

  test-client-csharp:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/csharp:ci-test

  test-client-java:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/java:ci-test

  test-client-python:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/python:ci-test

  test-client-lua:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/lua:ci-test

  test-client-serialio:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/serialio:ci-test

  test-client-websockets:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: bazel test //client/websockets:ci-test

  test-tools:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:2.6.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: ./.github/actions/build-setup
      - name: test
        run: |
          bazel test \
            //tools/krpctest:ci-test \
            //tools/krpctools:ci-test
