name: docs

on:
  push:
    branches:
      - docs

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/krpc/buildenv:3.3.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/build-setup
        with:
          long-version: false
      - name: fetch
        uses: krpc/krpc-core/.github/actions/bazel-fetch@main
      - name: ksp-lib
        uses: krpc/krpc-core/.github/actions/ksp-lib@main
        with:
          game: ksp
          version: 1.12.5
      - name: build
        run: |
          bazel build //doc:html
          mkdir github-pages
          echo "" > github-pages/.nojekyll
          (cd github-pages; unzip -q ../bazel-bin/doc/html.zip)
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages
      - name: deploy
        uses: actions/deploy-pages@v4
